/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade05.view;

import javax.swing.DefaultListModel;


public class RepeticaoComSlider extends javax.swing.JFrame {

    /**
     * Creates new form RepeticaoComSlider
     */
    public RepeticaoComSlider() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPasso = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        lblFim = new javax.swing.JLabel();
        lblValor3 = new javax.swing.JLabel();
        lblValor1 = new javax.swing.JLabel();
        lblValor2 = new javax.swing.JLabel();
        sldPasso = new javax.swing.JSlider();
        sldInicio = new javax.swing.JSlider();
        sldFim = new javax.swing.JSlider();
        btnCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstValores = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPasso.setText("Passo");
        getContentPane().add(lblPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lblInicio.setText("Inicio");
        getContentPane().add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 42, -1, -1));

        lblFim.setText("Fim");
        getContentPane().add(lblFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        lblValor3.setText("0");
        getContentPane().add(lblValor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        lblValor1.setText("0");
        getContentPane().add(lblValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        lblValor2.setText("0");
        getContentPane().add(lblValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        sldPasso.setMaximum(5);
        sldPasso.setMinimum(1);
        sldPasso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldPassoStateChanged(evt);
            }
        });
        getContentPane().add(sldPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        sldInicio.setMaximum(10);
        sldInicio.setMinimum(1);
        sldInicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldInicioStateChanged(evt);
            }
        });
        getContentPane().add(sldInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        sldFim.setMaximum(20);
        sldFim.setMinimum(11);
        sldFim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldFimStateChanged(evt);
            }
        });
        getContentPane().add(sldFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jScrollPane1.setViewportView(lstValores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 80, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
         
         //Cria uma nova lista.
         DefaultListModel lista = new DefaultListModel();
         
         //Adciona os alores dos sliders aos inteiros criados.
         int inicio = sldInicio.getValue();
         int fim = sldFim.getValue();
         int passo = sldPasso.getValue();
         
         //Faz-se um loop para adicionar os valores à lista.
         for(int i = inicio; i <= fim; i += passo){
             lista.addElement(i);
         }
         //Finalmente os valores são alocados.
         lstValores.setModel(lista);
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void sldInicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldInicioStateChanged
         //Adicionando os valores dos sliders aos seus labels respectivos.
         lblValor1.setText(Integer.toString(sldInicio.getValue()));
    }//GEN-LAST:event_sldInicioStateChanged

    private void sldFimStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldFimStateChanged
         //Adicionando os valores dos sliders aos seus labels respectivos.
         lblValor2.setText(Integer.toString(sldFim.getValue()));
    }//GEN-LAST:event_sldFimStateChanged

    private void sldPassoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldPassoStateChanged
         //Adicionando os valores dos sliders aos seus labels respectivos.
         lblValor3.setText(Integer.toString(sldPasso.getValue()));
    }//GEN-LAST:event_sldPassoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RepeticaoComSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RepeticaoComSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RepeticaoComSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RepeticaoComSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RepeticaoComSlider().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFim;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblPasso;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValor2;
    private javax.swing.JLabel lblValor3;
    private javax.swing.JList<String> lstValores;
    private javax.swing.JSlider sldFim;
    private javax.swing.JSlider sldInicio;
    private javax.swing.JSlider sldPasso;
    // End of variables declaration//GEN-END:variables
}
